### ISSUE TITLE
Hierarchical Clustering on t-SNE

### ISSUE THREAD

**Issue by SChoi97** [cellgeometry/heteromotility#2] opened 2020-11-11 10:43 UTC
Hi, thank you for this fantastic tool! It is proving useful in analysis of my motility videos on iPSC-derived myoblasts. 

As I am not too familiar with the specifics on t-SNE, **I was wondering what the logic is behind performing hierarchical clustering on the t-SNE**. Upon t-SNE clustering with my dataset, I do not find any obvious clusters (similar to the MEF clustering data from the original heteromotility paper). After hierarchical clustering, however, I have several groups which show different motility phenotypes and different proportions of my cells within different conditions within each cluster. 

Is hierarchical clustering after t-SNE common practice (does it make up for some weaknesses of t-SNE?)? I am in no way questioning your methodology, I simply would much appreciate an explanation on this so that I can make more sense of the graphs that I have generated from heteromotility.

Thanks again for this valuable resource and hope to hear back. 

Apologies if this is not the right forum to be posting this...

**Comment by jacobkimmel** [comment] 2020-11-11 20:12
Hi @SChoi97,

Thanks for your interest in `heteromotility`!

> I was wondering what the logic is behind performing hierarchical clustering on the t-SNE. 

We actually *don't* perform clustering on the t-SNE embedding. 
Rather, we cluster in the PCA embedding.

t-SNE is great for visualization, but it has a couple drawbacks. 
My favorite paper on this subject is a [beautiful interactive article at *Distill*](https://distill.pub/2016/misread-tsne/).
One of the drawbacks is that t-SNE is stochastic, so clustering on the t-SNE embedding will give you different results across runs. 
This isn't insurmountable, but it isn't great for reproducible research.
Another drawback is that t-SNE can often exaggerate or distort real structure in the data (e.g. play with the "three rings" example in the paper above). 
For these reasons, we prefer clustering in the PCA space where (1) our results are deterministic and reproducible and (2) merely a linear projection of the underlying data.

Because we cluster in the PCA embedding, your clusters may not match up exactly with the t-SNE visualization.

> After hierarchical clustering, however, I have several groups which show different motility phenotypes and different proportions of my cells within different conditions within each cluster.

Importantly hierarchical clustering will force your data to generate some clustering partition with the specified number of clusters.
If you specify `k = 4` clusters, the result will always contain `4` clusters.
You'll need to use your biological knowledge and a set of "cluster validity metrics" (e.g. Silhouette score, Calinski-Harabasz score) to determine the optimal cluster number.
For the original Heteromotility paper, we used the top ranked cluster number across a set of different indices (`NbClust` in `R` will run these for you).

After you've optimized your cluster number, those clusters might not appear "obvious" in the t-SNE embedding for the reasons noted above.

> Is hierarchical clustering after t-SNE common practice (does it make up for some weaknesses of t-SNE?)

t-SNE itself isn't a clustering procedure, just a visualization procedure.
If you only run t-SNE, your cells aren't actually assigned a cluster label, just a coordinate in a 2D space. 
This is great for plotting, but it doesn't help you quantify differences across cell states in your data!

We used hierarchical clustering to assign these labels because it's fairly simple. Many other methods exist (e.g. k-Means, Leiden community detection, etc.). 
Using these methods in combination with a visualization technique (PCA, t-SNE, UMAP, InfoMap) is very common for high dimensional measurements (e.g. cell morphology, single cell genomics, and motility :).

> Apologies if this is not the right forum to be posting this...

Happy to answer any other questions!

Best,
J

**Comment by SChoi97** [comment] 2020-11-12 13:35
Thank you very much @jacobkimmel  for the detailed explanation! I really appreciate it. 

I now understand that t-SNE is for visualisation whilst hierarchical clustering is useful for extracting useful information out of the data. 

However, does that mean if the t-SNE graph does not show any distinct clusters it is essentially redundant? Both t-SNE and hierarchical clustering essentially places 'similar' points together, albiet via different algorithms. If t-SNE is not able to distinguish clearly between different 'motility states' whilst hierarchical clustering does (clusters show drastically different motility phenotypes e.g. slow + less time moving vs fast + always moving), what kind of conclusions can we make from a biological perspective with respect to how different these motility phenotypes really are? Can we really say that these motility phenotypes are drastically different when the t-SNE is not able to distinctly distinguish between clusters? I am bringing up this point as it may not be very convincing to conclude that there are distinct motility phenotypes present purely based on hierarchical clustering when it is not apparent in the t-SNE.

Any opinion regarding this would be greatly appreciated!

**Comment by jacobkimmel** [comment] 2020-11-12 21:40
>  I am bringing up this point as it may not be very convincing to conclude that there are distinct motility phenotypes present purely based on hierarchical clustering when it is not apparent in the t-SNE.

t-SNE does indeed try to embed points that are closer in the measurement space more closely in the projection space. However, it is not a clustering algorithm and therefore shouldn't be used to determine whether or not two groups of cells are sufficiently different enough to be interesting.
t-SNE can fail to capture meaningful differences in your data for all sorts of reasons, including poor hyper parameter settings, optimization issues, or high dimensionality of your input space, so the plots shouldn't be over-interpreted.
As a trick, try removing some of the features that don't vary across your clusters before embedding.
I often found that the turning directions were highly variable, but not informative, so we removed them before embedding in the original paper.

In our work, we found that motility states were rarely discrete within the same cell type. 
Even in the context of a dynamic stem cell activation, we found that motility progressed smoothly from one state to the next.
Discretizing a continuous process into a set of clusters is a convenient approximation that allows us to describe continuous biology, but rarely will biology be as discrete as our cluster partition within a given cell type.
See: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005927#pcbi-1005927-g004

The only truly distinct states we observed were when we compared across cell types.
This is consistent with other measures of cell state using e.g. single cell RNA-seq -- most changes within a cell type are continuous, while differences across cell types are often discrete.

It's difficult to know whether the variation in your system is "meaningful" *ex ante*, or whether clustering is a reasonable approximation in your case.
Rather than give you a simple yes or no, I'll offer a decision tree :)

1. Does the degree of variation you capture across clusters appear meaningful in your context? Are the differences large enough to warrant consideration in light of your question?
2. If **1** is yes, are the clusters more distinct than continuous?
3. *A* If **2** is yes -- clustering is likely appropriate, and you could try tricks like I suggest above to generate a visualization.
3. *B* If **2** is no and the clusters seem to capture a gradient of changes in feature values, your data might be continuous. Consider using a pseudotemporal ordering method like diffusion pseudotime to generate a continuous, rather than discrete, coordinate system for your data.

If you can share more about what you're working on, I might be able to offer better advice.

Hope that helps!
Jacob

**Comment by jacobkimmel** [comment] 2020-11-24 20:25
Closing as conversation moved off-line

**Closed as completed by jacobkimmel** 2020-11-24 20:25 UTC
